feat(WRN-1350): support gradle runinstall
containerbase/runinstall pull request #21
Opened 2024-09-09 12:19 UTC by PhilipAbed

2024-09-11 14:00 UTC, nabeelsaabna requested changes
add/improve Docs
add JsDocs for "types"

2024-09-12 16:32 UTC, nabeelsaabna requested changes

2024-09-15 06:13 UTC, PhilipAbed commented on src/tools/gradle.js
> + */
object type of ToolConstraint. is there another way to do it ? :D

2024-09-15 06:15 UTC, PhilipAbed commented on README.md
> +Runinstall has the propriety code to extract the constraints from the supported tools, and it utilizes renovate and install-tool in order to generate commands and install them.
```suggestion
Runinstall extracts version constraints of package managers, and utilizes Renovate and install-tool to generate commands to install the tool version that the project requires.
```

2024-09-15 06:16 UTC, PhilipAbed commented on README.md
> +Runinstall has the propriety code to extract the constraints from the supported tools, and it utilizes renovate and install-tool in order to generate commands and install them.
try now

2024-09-16 11:14 UTC, nabeelsaabna approved these changes
Docs to be refined in a new PR since it's not a Gradle related change

2024-09-16 11:14 UTC, merged